name: CI/CD

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: ./ansible_collections/mrichardson03/panos

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./ansible_collections/mrichardson03/panos

      - name: Set up Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.6.8

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          python -m pipenv install --dev --system

      - name: Check format
        run:
          make check-format

      - name: ansible-test sanity
        run:
          make sanity

      - name: ansible-test units
        run:
          make units

  automerge:
    name: Auto-merge
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge pull requests from dependabot (patches only)
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
          PRESET: DEPENDABOT_PATCH
