name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: ./ansible_collections/mrichardson03/panos

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./ansible_collections/mrichardson03/panos

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.6.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Check pipenv cache
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies (if no cache hit)
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Check format
        run:
          pipenv run make check-format

      - name: ansible-test sanity
        run:
          pipenv run make sanity

      - name: ansible-test units
        run:
          pipenv run make units

      - name: ansible-lint roles
        run:
          pipenv run make ansible-lint

      - name: ansible-galaxy collection build
        run:
          pipenv run make build
